FROM nginx:alpine
COPY index.html /usr/share/nginx/html/
COPY bootstrap /usr/share/nginx/html/bootstrap
COPY html /usr/share/nginx/html/html
COPY img /usr/share/nginx/html/img
COPY js /usr/share/nginx/html/js
