services:
  database:
    build:
      context: ./database
      dockerfile: Dockerfile
    image: library-db
    ports:
      - "1433:1433"
    environment:
      SA_PASSWORD: "YourStrong!Passw0rd"
      ACCEPT_EULA: "Y"
    volumes:
      - mssql_data:/var/opt/mssql

  backend:
    build:
      context: ./library-app
      dockerfile: Dockerfile
    image: library-backend
    ports:
      - "5000:80"
    depends_on:
      - database
    environment:
      - ConnectionStrings__DefaultConnection=Server=database;Database=LibraryAppDb;User=sa;Password=YourStrong!Passw0rd;

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    image: library-client
    ports:
      - "8080:80"
    depends_on:
      - backend

volumes:
  mssql_data:
