services:
  database:
    build:
      context: ./database
      dockerfile: Dockerfile
    container_name: library-database
    environment:
      SA_PASSWORD: "YourStrongPassword123"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
  
  server:
    build:
      context: ./library-app
      dockerfile: library-app/Dockerfile
    container_name: library-server
    ports:
      - "8080:8080"
      - "8081:8081"
    depends_on:
      - database
    environment:
      - ConnectionStrings__DefaultConnection=Server=database;Database=LibraryDb;User Id=sa;Password=YourStrongPassword123;

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: library-client
    ports:
      - "3000:3000"
    depends_on:
      - server
